version: '3'

services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.33.4
    restart: always
    ports:
      - "9000:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    depends_on:
      - postgres
  
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - postgres
      - graphql-engine
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SENDGRID_EMAIL: ${SENDGRID_EMAIL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

volumes:
  redis_data:
  postgres_data: